name: epub_view_example
description: Example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  internet_file:
    git:
      url: https://github.com/Danilz-2706/internet_fil.git
      ref: main

  flutter:
    sdk: flutter
  epub_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/
  uses-material-design: true
